"""empty message

Revision ID: 70ec9924c92f
Revises: 892d4ced77bf
Create Date: 2022-03-04 22:19:17.088704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ec9924c92f'
down_revision = '892d4ced77bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_table_list_id_fkey', 'item_table', type_='foreignkey')
    op.drop_column('item_table', 'list_id')
    op.drop_constraint('shopinglist_table_user_id_fkey', 'shopinglist_table', type_='foreignkey')
    op.drop_column('shopinglist_table', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopinglist_table', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shopinglist_table_user_id_fkey', 'shopinglist_table', 'users', ['user_id'], ['id'])
    op.add_column('item_table', sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_table_list_id_fkey', 'item_table', 'shopinglist_table', ['list_id'], ['id'])
    # ### end Alembic commands ###
