"""empty message

Revision ID: 892d4ced77bf
Revises: a1367dcbc698
Create Date: 2022-03-04 22:08:25.798900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892d4ced77bf'
down_revision = 'a1367dcbc698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_table', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_table', 'shopinglist_table', ['list_id'], ['id'])
    op.add_column('shopinglist_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopinglist_table', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopinglist_table', type_='foreignkey')
    op.drop_column('shopinglist_table', 'user_id')
    op.drop_constraint(None, 'item_table', type_='foreignkey')
    op.drop_column('item_table', 'list_id')
    # ### end Alembic commands ###
